### ISSUE TITLE
Can you please publish a gradio demo that will take text and video as input and generate output video

### ISSUE THREAD

**Issue by FurkanGozukara** [haoyuhsu/autovfx#1]
That would be amazing and so many people can use it easily with such app

Of course requirements will be installed

**Comment by haoyuhsu** [comment]
Great suggestions! I'll be sure to add them to my to-do list. 

Additionally, since several steps in the simulation pipeline (such as surface reconstruction, HDR lighting estimation, and Blender simulation and rendering) can be very time-consuming, I need to carefully consider how to design this app effectively.

**Comment by FurkanGozukara** [comment]
@haoyuhsu awesome i hope you do. I will make advertisement of your project if you make such gradio app every platform i have

e.g. my youtube : https://www.youtube.com/@SECourses/videos
