### ISSUE TITLE
Is it possible for the current code to implement the editing operations described in the paper within the Waymo scenario?

### ISSUE THREAD

**Issue by fcdml** [haoyuhsu/autovfx#2]

**Comment by haoyuhsu** [comment]
Hi~

The current implementation is designed to be generalized; however, you can edit Waymo scenes by following these steps:
- Download the preprocessed dataset for scenario 9385 from [here](https://drive.google.com/drive/folders/1tT1YSppo2lC4Let_vIIKcsr6OWlSFmqX?usp=sharing). The reconstructed mesh is included in the folder.
- Train 3dgs & sugar using the same script provided in README.
- Download the blender road scene assets from [here](https://drive.google.com/drive/folders/1t-JXV328NahwbqwSgorboUHAUME_p8-R?usp=sharing) and place them under `_cache` folder. Please note that this asset bank is the same as ChatSim.
- During the simulation, several parameters are required:
    - `--custom_traj_name` set to `transforms_001`
    - `--scene_scale` set to `1.0` because the poses are represented in real-world scale.
    - `--waymo_scene` should be set.
    - `--is_uv_mesh` should not be set.
    - `--scene_mesh_path` set to the path to `partial_mesh.ply`. Note that `partial_mesh.ply` is reconstructed using the first 40 frames following ChatSim, while `complete_mesh.ply` is reconstructed using the entire scenario.

**Comment by haoyuhsu** [comment]
If you would like to preprocess arbitrary Waymo scenarios, please refer to [StreetSurf](https://github.com/PJLab-ADG/neuralsim/blob/main/docs/methods/streetsurf.md) since I obtained the camera poses and reconstructed mesh from this repo. Specifically, I used this setting without lidar cues: **_Multi-view reconstruction without LiDAR (i.e. multi-view posed images + inferred cues)_**.

If you found issues during the data processing, please refer to my previous experience from [here](https://github.com/PJLab-ADG/neuralsim/issues/62).
